### ISSUE TITLE
Inconsistency with other Datadog actions

### ISSUE THREAD

**Issue by tcs-cclaflin** [DataDog/test-visibility-github-action#4]
This looks to be a new action, just a heads up that it looks to be inconsistent with other existing datadog actions we already use.

https://github.com/DataDog/datadog-static-analyzer-github-action
https://github.com/DataDog/datadog-sca-github-action

Makes it easier to maintain across the board standards for our datadog actions when they use consistent variables and such.

Thank you for considering this.

**Comment by fermayo** [comment]
Thank you @tcs-cclaflin for the feedback. You are completely right and we'll address this soon.

**Comment by nikita-tkachenko-datadog** [comment]
Hi @tcs-cclaflin, thank you for reporting this!
This action's inputs have been updated in the latest release v1.0.6 (`api-key` -> `api_key`, `service-name` -> `service`).
This isn't in line with the static analysis actions yet, but those will be updated as well to ensure consistency across all Datadog's actions.
The older inputs have been deprecated, but are still available for use.

**Comment by tcs-cclaflin** [comment]
@nikita-tkachenko-datadog  Thanks for looking into this. Just my 2 cents but I actually like the dd_ prefix better since it is more inline with the datadog variables we use in most of the datadog products (APM, Logs, etc) so it's actually what we are more familiar working with.

**Comment by nikita-tkachenko-datadog** [comment]
Yes, that makes sense. But the thing is that the static analysis actions are themselves recent and the older actions use a different naming scheme (without the `dd_` prefix). I feel like it'd be unfair to the users of those actions to change the naming there 🙂
