### ISSUE TITLE
The installer script does not lock versions for its dependencies

### ISSUE THREAD

**Issue by offbyone** [DataDog/test-visibility-github-action#6]
The installer script at https://install.datadoghq.com/scripts/install_test_visibility_v1.sh does not make any versioning guarantees; it performs unversioned installations of the libraries from the respective packaging systems. 

This means that if a new release disrupts workflows that use this action, there is no mechanism for reverting to a previous version in order to unblock.

**Comment by nikita-tkachenko-datadog** [comment]
Hi @offbyone, this is a valid concern, thank you for reporting it!
The latest action release [v1.0.6](https://github.com/DataDog/test-visibility-github-action/releases/tag/v1.0.6) adds a set of optional inputs that allow to lock tracing library versions.
